### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by erwanp** [radis/hitemp#1]
- [ ] WebGL graphics to visualize the database ([Bokeh example](http://docs.bokeh.org/en/0.10.0/docs/user_guide/webgl.html))

- [ ] Main example not working anymore 
```
import hitemp
df = hitemp.fetch("OH")
```

- [ ] publish on Pypi
